-- https://sqliteonline.com/

DROP TABLE IF EXISTS Expenses;
CREATE TABLE Expenses (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name text NOT NULL,
    Value real NOT NULL,
    Data date NOT NULL,
    TagId INTEGER NULL,
    CONSTRAINT `FK_Expenses_Tag` FOREIGN KEY (`TagId`) REFERENCES `Tags` (`Id`) NULL ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Tags;
CREATE TABLE Tags (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name text NOT NULL
);