version: 0.1.{build}
branches:
  only:
  - master
  - dev
image:
 - Visual Studio 2017
configuration:
 - Debug
 - Release
platform:
 - x86
nuget:
  account_feed: true
  project_feed: true
build:
  project: MyExpenses.sln
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
notifications:
- provider: Email
  to:
  - lfmachadodasilva@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
before_build:
  - nuget restore
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"Domain\Tests\bin\x86\Debug\MyExpenses.Domain.Tests.dll" -output:"TestResultDomain.xml"
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"Infrastructure\Tests\bin\x86\Debug\MyExpenses.Infrastructure.Tests.dll" -output:"TestResultInfrastructure.xml"
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"Application\Tests\bin\x86\Debug\MyExpenses.Application.Tests.dll" -output:"TestResultApplication.xml"
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"Util\Tests\bin\x86\Debug\MyExpenses.Util.Tests.dll" -output:"TestResultUtil.xml"
after_test:
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - pip install git+git://github.com/codecov/codecov-python.git
 - codecov -f "TestResultDomain.xml" -t 81c4ac46-b5bc-4d0d-8c4f-4de04812e6e3 -X gcov
 - codecov -f "TestResultInfrastructure.xml" -t 81c4ac46-b5bc-4d0d-8c4f-4de04812e6e3 -X gcov
 - codecov -f "TestResultApplication.xml" -t 81c4ac46-b5bc-4d0d-8c4f-4de04812e6e3 -X gcov
 - codecov -f "TestResultUtil.xml" -t 81c4ac46-b5bc-4d0d-8c4f-4de04812e6e3 -X gcov
artifacts:
 - path: artifacts\**\*.*