version: 0.1.{build}
branches:
  only:
  - master
  - dev
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x86
nuget:
  account_feed: true
  project_feed: true
build:
  project: MyExpenses.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
notifications:
- provider: Email
  to:
  - lfmachadodasilva@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
before_build:
  - nuget restore