version: 0.1.{build}
configuration:
- Debug
- Release
platform:
- x86
before_build:
  - nuget restore
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
notifications:
- provider: Email
  to:
  - lfmachadodasilva@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true