version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- x86
- x64
nuget:
  account_feed: true
  project_feed: true
before_build:
  - nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal