
DROP TABLE IF EXISTS Expenses;
CREATE TABLE Expenses (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name text NOT NULL,
    Value real NOT NULL,
    Data date NOT NULL
);

DROP TABLE IF EXISTS Tags;
CREATE TABLE Tags (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name text NOT NULL
);

DROP TABLE IF EXISTS Expenses_Tags;
CREATE TABLE Expenses_Tags (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ExpenseId INTEGER NOT NULL,
    TagId INTEGER NOT NULL,
    CONSTRAINT `Expenses_Tags_Expense` FOREIGN KEY (`ExpenseId`) REFERENCES `Expenses` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `Expenses_Tags_Tag` FOREIGN KEY (`TagId`) REFERENCES `Tags` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE
);